#!/bin/bash
echo "The first name entered is $1"
echo "The middle name entered is $2"
echo "The last name entered is $3"
echo "The full name is $1 $2 $3"
echo "This data is saved under $0 file"
echo "The first argumnet is $1"
echo "The second argumnet is $2"
echo "The third argumnet is $3"
echo "The total number of argumnet is - $#"
echo "The processID of current running process is - $$"
echo "The processID of last command is - $!"
echo "Status of last exceuted command is -  $?"
echo "All arguments passed as a string: $*"
echo "All arguments passed as a string & stored in a array format: $@"
